server:
  servlet:
    context-path: /api

spring:
  application:
      name: herborder
  datasource:
    url: jdbc:postgresql://localhost:5435/herborders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: mail-user
    password: mail-password
    properties.mail.smtp:
      auth: tls
      starttls.enable: true
  security.user:
    name: admin
    password: admin

flyway.datasource:
  url: jdbc:postgresql://localhost:5435/herborders
  username: postgres
  password: postgres

